Defaults: 
  - &lottieInteractive
    default: "none"
    options: [
      { label: "None", value: "none" },
      { label: "Play on Scroll", value: "playOnScroll" },
      { label: "Sync with Scroll", value: "syncWithScroll" },
      { label: "Play on Hover", value: "playOnHover" },
      { label: "Play on Hold", value: "playOnHold" },
      { label: "Play on Hold (reverse on leave)", value: "playOnHold2" },
      { label: "Play on Click", value: "playOnClick" },
      { label: "Toggle on Click", value: "toggleOnClick" },
      { label: "Cursor Seek Vertical", value: "cursorSeekVertical" },
      { label: "Cursor Seek Horizontal", value: "cursorSeekHorizontal" }
    ]
  - &graphicPositions
    {
      options: [
        "above heading",
        "above content",
        "left",
        "right",
        "top left",
        "top right",
        "bottom left",
        "bottom right",
        "below content",
      ]
    }
  - &graphic
    {
      label: graphic,
      name: graphic,
      widget: list,
      max: 1,
      types:
        [
          { 
            label: Image, 
            name: image-object, 
            widget: object, 
            fields: [
              { label: Position, name: position, widget: select, <<: *graphicPositions, default: "above heading"},
              { label: Image, name: image, widget: image }
            ]
          },
          { 
            label: Animation,
            name: animation-object, 
            widget: object, 
            fields: [
              { label: Position, name: position, widget: select, <<: *graphicPositions, default: "above heading"},
              { label: Lottie URL, name: lottie, widget: string },
              { label: Autoplay, name: autoplay, widget: boolean, default: true },
              { label: Loop, name: loop, widget: boolean, default: true },
              { label: Show Controls, name: controls, widget: boolean, default: false },
              { label: Interactive, name: interactive, widget: select, <<: *lottieInteractive }
            ]
          },
        ]
      }
  - &sections
    {
      label: Sections,
      label_singular: Section,
      name: sections,
      widget: list,
      summary: '{{fields.heading}}',
      fields:
        [
          { label: Text Alignment, name: align, widget: select, options: ["start", "center", "end"], default: "start"},
          { label: Heading, name: heading, widget: string },
          { label: SubHeading, name: subheading, widget: string, required: false },
          { label: Content, name: content, widget: markdown, editor_components: ['button', 'icon-box'] },
          { <<: *graphic }
        ]
    }

backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Hero Carousel,
              name: carousel,
              collapsed: true,
              widget: object,
              fields:
                [
                  { label: Show Arrows, name: showControls, widget: boolean, default: true },
                  { label: Show Indicators, name: showIndicators, widget: boolean, default: true },
                  {
                    label: Slides,
                    label_singular: Slide,
                    name: slides,
                    widget: list,
                    min: 1,
                    fields:
                      [
                        { label: Align Content, name: align, widget: select, options: ["left", "center", "right"], default: "center"},
                        { label: Image, name: image, widget: image },
                        { label: Heading, name: heading, widget: markdown, minimal: true, editor_components: [], default: '# **Heading**' },
                        { label: SubHeading, name: subheading, widget: markdown, minimal: true, editor_components: [] },
                      ],
                  },
                ],
            }
          - {
              label: Products,
              label_singular: Product,
              name: products,
              widget: list,
              summary: '{{fields.heading}}',
              min: 1,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Heading, name: heading, widget: string },
                  { label: Content, name: content, widget: markdown, editor_components: ['button'] },
                ],
            }
          - { <<: *sections }
          - {
              label: Team Section,
              name: team,
              collapsed: true,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Text, name: text, widget: markdown, minimal: true },
                  { label: Show Arrows, name: showControls, widget: boolean, default: true },
                  {
                    label: Team Members,
                    label_singular: Team Member,
                    name: members,
                    widget: list,
                    fields:
                      [
                        { label: Name, name: name, widget: string},
                        { label: Role, name: role, widget: string },
                        { label: Image, name: image, widget: image },
                        { label: Description, name: description, widget: markdown, minimal: true, editor_components: [] },
                      ],
                  },
                ],
            }

      - file: "src/pages/announcements.md"
        label: "Announcements"
        name: "announcements"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "announcement-page",
            }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "File", name: "file", widget: "file", required: false }

      - file: "src/pages/whitepapers/index.md"
        label: "White Papers"
        name: "whitepapers-index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "white-papers",
            }
          - { label: "Title", name: "title", widget: "string", default: "White Papers" }
          - { label: "Subheading", name: "subheading", widget: "string", required: false }
          - { label: "Section Heading", name: "heading", widget: "string" }
          - { label: "Section Text", name: "body", widget: "markdown", required: false }
          - {
              label: Categories,
              label_singular: Category,
              name: categories,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string},
                  { label: Animation URL, name: lottie, widget: string, required: false }
                ],
            }

  - name: "whitepapers"
    label: "White Papers"
    label_singular: "White Paper"
    folder: "src/pages/whitepapers/papers"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "white-paper",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subheading", name: "subheading", widget: "string" }
      - { 
          label: "Categories",
          name: "selectedCategories", 
          widget: "relation",
          multiple: true,
          min: 1,
          collection: "pages", 
          file: "whitepapers-index", 
          value_field: "categories.*.name", 
          search_fields: ["categories.*.name"]
        }
      - { label: "Icon", name: "icon", widget: "fontawesome-solid", default: "fas apple-whole" }
      - { <<: *sections }
      - { 
          label: "Related Papers",
          name: "relatedPapers", 
          widget: "relation",
          multiple: true,
          required: false,
          collection: "whitepapers",
          value_field: "title", 
          search_fields: ["title"]
        }

  - name: "docs"
    label: "Docs"
    label_singular: "Doc"
    editor:
      preview: false
    folder: "src/docs"
    create: true
    slug: "{{fields.route}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Route", name: "route", widget: "string", default: "/docs/[page-name]" }
      - { label: "Menu", name: "menu", widget: "string", required: false }
      - { label: "Hidden", name: "hidden", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
    - file: "src/style/config/theme-colors.md"
      label: "Theme Colors"
      name: "theme-colors"
      fields:
        - { label: "Primary", name: "primary", widget: "color" }
        - { label: "Secondary", name: "secondary", widget: "color" }
        - { label: "Success", name: "success", widget: "color" }
        - { label: "Info", name: "info", widget: "color" }
        - { label: "Warning", name: "warning", widget: "color" }
        - { label: "Danger", name: "danger", widget: "color" }